### ISSUE TITLE
Wrong route cause example crash

### ISSUE THREAD

**Issue by bingtaoli** [loggerhead/lhttpd#3]
`main.o` core because of segment fault while browser gives a bad request of `/static/static/css/base.css`, I change the `index.html, href="static/css/base.css"` to `"css/base.css"` and the `main.o` works the right way, I think the server should not core while a bad request comes.

**Comment by loggerhead** [comment]
@bingtaoli which example has this issue?

**Comment by bingtaoli** [comment]
static_page

**Comment by loggerhead** [comment]
@bingtaoli I can't reproduce the problem. Can you give me more details?

**Comment by bingtaoli** [comment]
run main.o to start the server, and try http://0.0.0.0:9999/static/index.html in your browser

**Comment by loggerhead** [comment]
@bingtaoli Still, no crash. It would be help if you can show me the code you changed and the logging of `lhttpd` .
